# Generated by Django 6.1 on 2026-08-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='status',
            field=models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('TESTING', 'Testing'), ('COMPLETED', 'Completed')], default='TODO', max_length=20),
        ),
    ]
