# Generated by Django 6.1 on 2026-08-14 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_department_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_name', models.CharField(default='Flow Guard', max_length=150)),
                ('language', models.CharField(default='English', max_length=50)),
                ('timezone', models.CharField(default='UTC+5:30 (IST)', max_length=100)),
                ('date_format', models.CharField(default='MM/DD/YYYY', max_length=30)),
                ('week_start', models.CharField(default='Monday', max_length=20)),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('task_assigned', models.BooleanField(default=True)),
                ('task_completed', models.BooleanField(default=False)),
                ('bug_reported', models.BooleanField(default=True)),
                ('project_updates', models.BooleanField(default=True)),
                ('weekly_digest', models.BooleanField(default=False)),
                ('mention_alerts', models.BooleanField(default=True)),
                ('appearance', models.CharField(choices=[('LIGHT', 'Light'), ('DARK', 'Dark'), ('SYSTEM', 'System')], default='LIGHT', max_length=20)),
                ('accent_color', models.CharField(default='blue', max_length=30)),
                ('compact_mode', models.BooleanField(default=False)),
                ('sidebar_collapsed', models.BooleanField(default=False)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Setting',
                'verbose_name_plural': 'User Settings',
            },
        ),
    ]
